# Site settings
title: De-Dale
author: Les labyrinthuses
description: >
  Méandres de l'imaginaire
twitter_username: de-dale
github_username: de-dale
slack: de-dale
rss: rss

# Build Setting
theme: minima
port: 9000

# Env Settings
show_excerpts: true
show_drafts: true
header_pages:
 - index.html
 - all.html
 - about.md

collections:
  category:
    output: true
    permalink: /:name/index.html
  drafts:
    output: true
    permalink: /:categories/:year/:month/:day/:title:output_ext

defaults:
  -
    scope:
      path: ""
      type: drafts
    values:
      layout: draft

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock