# Site settings
title: De-Dale
author: Les labyrinthuses
description: >
  Méandres de l'imaginaire
twitter_username: de-dale
github_username: de-dale
slack: de-dale
rss: rss

# Build Setting
theme: minima
port: 9000

# Env Settings
show_excerpts: true
header_pages:
 - index.html
 - all.html
 - about.md

collections:
  category:
    output: true
    permalink: /:name/index.html

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock